version: '3.8'
services:
  db:
    image: mysql:8.0
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/config:/etc/mysql/conf.d
      - ./mysql/init:/docker-entrypoint-initdb.d

  backend:
    build: ./server
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080
    environment:
      - dbUrl=root:123456@tcp(db)/blog?charset=utf8
    volumes:
      - ./server/config.yml:/app/config.yml

  frontend:
    build: ./admin
    ports:
      - 8081:80